import argparse
import os
import subprocess
import sys
from datetime import datetime

from github import Github, GithubException

def run_command(command, check=True):
    """Runs a command, prints its output, and returns the stripped stdout."""
    print(f"Running command: {' '.join(command)}")
    try:
        result = subprocess.run(
            command, capture_output=True, text=True, check=check, encoding="utf-8"
        )
        if result.stdout:
            print(result.stdout)
        if result.stderr:
            print(result.stderr, file=sys.stderr)
        return result.stdout.strip()
    except subprocess.CalledProcessError as e:
        print(f"Error running command: {' '.join(command)}", file=sys.stderr)
        print(e.stdout, file=sys.stderr)
        print(e.stderr, file=sys.stderr)
        raise


def main():
    parser = argparse.ArgumentParser(description="Create a PR for dependency updates if needed.")
    parser.add_argument("--workspace", required=True, help="GitHub workspace path.")
    parser.add_argument("--deps-file-path", required=True, help="Relative path to the dependency file to check.")
    parser.add_argument("--base-branch", required=True, help="The base branch for the pull request.")
    args = parser.parse_args()

    os.chdir(args.workspace)

    # 1. Check for changes
    status_output = run_command(["git", "status", "--porcelain", args.deps_file_path])
    if not status_output:
        print(f"No changes detected in {args.deps_file_path}. No PR will be created.")
        return

    print(f"Changes detected in {args.deps_file_path}. Proceeding to create a PR.")

    # 2. Get required environment variables
    github_token = os.getenv("GITHUB_TOKEN")
    repo = os.getenv("GITHUB_REPOSITORY")
    if not github_token or not repo:
        print("Error: GITHUB_TOKEN and GITHUB_REPOSITORY environment variables must be set.", file=sys.stderr)
        sys.exit(1)

    # 3. Configure Git
    run_command(["git", "config", "user.name", "github-actions[bot]"])
    run_command(["git", "config", "user.email", "41898282+github-actions[bot]@users.noreply.github.com"])

    # 4. Create and push a new branch
    timestamp = datetime.utcnow().strftime("%Y%m%d%H%M%S")
    branch_name = f"check-all-libraries-{timestamp}"

    run_command(["git", "checkout", "-b", branch_name])
    run_command(["git", "add", args.deps_file_path])
    run_command(["git", "commit", "-m", "chore: Update actual dependencies list"])
    run_command(["git", "push", "origin", branch_name])

    # 5. Create the Pull Request using PyGithub
    try:
        print("Authenticating with GitHub...")
        g = Github(github_token)
        repo_obj = g.get_repo(repo)

        title = "[Automated] Update Actual Dependencies List"
        body = "This PR was auto-generated by the 'Dependencies Check For All Libraries' workflow.\nIt contains updates to the `ActualDepsList.adeps` file based on the latest dependency scan."

        print(f"Creating pull request to merge '{branch_name}' into '{args.base_branch}'...")
        pr = repo_obj.create_pull(
            title=title,
            body=body,
            head=branch_name,
            base=args.base_branch,
        )
        print(f"Successfully created pull request: {pr.html_url}")

    except GithubException as e:
        print(f"PyGithub API Error: {e.status} {e.data.get('message', '')}", file=sys.stderr)
        print(f"Response Body: {e.data}", file=sys.stderr)

        # Provide specific hints for common errors
        message = e.data.get("message", "")
        if "Resource not accessible by personal access token" in message:
            print("\n--- HINT ---", file=sys.stderr)
            print("This '403 Forbidden' error indicates a permission issue with your Personal Access Token (PAT).", file=sys.stderr)
            print("1. For a PERSONAL repository, ensure your PAT has the 'repo' scope.", file=sys.stderr)
            print("2. For an ORGANIZATION repository using SAML SSO, you must 'Enable SSO' or 'Authorize' the token for that organization.", file=sys.stderr)
            print("You can manage your PAT settings and permissions on GitHub.", file=sys.stderr)
            print("--- HINT ---\n", file=sys.stderr)
        elif "not all refs are readable" in message:
            print("\n--- HINT ---", file=sys.stderr)
            print("This '422 Validation Failed' error means the token cannot read one of the branches for the PR.", file=sys.stderr)
            print(f"  - Head branch: {branch_name}", file=sys.stderr)
            print(f"  - Base branch: {args.base_branch}", file=sys.stderr)
            print("Please check the following:", file=sys.stderr)
            print("1. Ensure the base branch (e.g., 'main') exists on the remote repository.", file=sys.stderr)
            print("2. If using a 'Fine-grained' PAT, ensure it has 'Contents: Read-only' permissions for the repository.", file=sys.stderr)
            print("3. If using a 'Classic' PAT, ensure it has the 'repo' scope (or at least 'public_repo' for public repositories).", file=sys.stderr)
            print("--- HINT ---\n", file=sys.stderr)

        sys.exit(1)

if __name__ == "__main__":
    # For local testing:
    # 1. Create a `.env` file in the repository root with:
    #    GITHUB_TOKEN=your_github_pat_here
    #    GITHUB_REPOSITORY=your_owner/your_repo
    # 2. Manually change the deps file (e.g., Source/ActualDependencies/ActualDepsList.adeps)
    # 3. Run the script from the repository root: `uv run python scripts/src/scripts/create_pr_for_deps.py`
    if len(sys.argv) == 1:
        print("--- Running in local test mode with default arguments ---")
        try:
            from dotenv import load_dotenv
            load_dotenv()
        except ImportError:
            print("Warning: python-dotenv not found. Please install it (`uv pip install python-dotenv`) to use .env files for local testing.", file=sys.stderr)

        # Check for environment variables after attempting to load from .env
        if not os.getenv("GITHUB_TOKEN") or not os.getenv("GITHUB_REPOSITORY"):
            print("Error: For local testing, create a .env file in the root directory with GITHUB_TOKEN and GITHUB_REPOSITORY, or set them as environment variables.", file=sys.stderr)
            sys.exit(1)

        sys.argv.extend([
            "--workspace", ".",
            "--deps-file-path", "Source/ActualDependencies/ActualDepsList.adeps",
            "--base-branch", "main"
        ])
    main()
