name: Expected Dependencies Check For Modified Libraries

on:
  pull_request:
    # Only listen for label changes on PRs
    types: [labeled]

permissions:
  contents: write

jobs:
  DependenciesCheckModifiedLibraries:
    # Only run when the added label is exactly 'RunCI'
    if: ${{ github.event.label.name == 'RunCI' }}
    runs-on: [ci-pc]

    # Define the base path environment variable
    env:
      LV_PYTHON_SCRIPTS_PATH: 'C:\ProgramData\HawkeyeScripts'
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Detect LabVIEW
        shell: powershell
        run: |
          python "${{ env.LV_PYTHON_SCRIPTS_PATH }}\scripts\src\scripts\detect_labview.py" "${{ github.workspace }}"

      - name: Generate changed files list and changed libraries list
        shell: powershell
        run: |
          cd ${{ env.LV_PYTHON_SCRIPTS_PATH }}\scripts
          uv sync
          cd ${{ env.LV_PYTHON_SCRIPTS_PATH }}\
          scripts\.venv\Scripts\activate
          uv run python -u ${{ env.LV_PYTHON_SCRIPTS_PATH }}\scripts\src\scripts\generate_changed_files_list.py --workspace_root "${{ github.workspace }}" --base_branch "origin/${{ github.event.pull_request.base.ref }}" --head_branch "HEAD"

      - name: Unexpected Dependencies Check
        shell: powershell
        # True argument in the gcli command args represents Checking Only Modified Libraries
        run: |
          $viPath = "$env:LV_PATH\vi.lib\Hawkeye\AutomatedChecks\UnexpectedDepsCheck.vi"
          g-cli -v --lv-ver $env:LV_VERSION --arch $env:LV_BITNESS "$viPath" -- "${{ github.workspace }}" "True"

      - name: Update Actual Deps List and Circular Dependencies Check
        shell: powershell
        # Update the Actual Deps list for modified libraries and then perform circular dependencies check. 
        # True argument in the gcli command args represents Update only for Modified Libraries
        run: |
          $viPath = "$env:LV_PATH\vi.lib\Hawkeye\AutomatedChecks\UpdateActualDepsList.vi"
          g-cli -v --lv-ver $env:LV_VERSION --arch $env:LV_BITNESS "$viPath" -- "${{ github.workspace }}" "True"
          cd ${{ env.LV_PYTHON_SCRIPTS_PATH }}\scripts
          uv sync
          cd ${{ env.LV_PYTHON_SCRIPTS_PATH }}\
          scripts\.venv\Scripts\activate
          uv run python -u ${{ env.LV_PYTHON_SCRIPTS_PATH }}\scripts\src\scripts\sort_actual_deps_list.py "${{ github.workspace }}\Source\ActualDependencies"
          uv run python -u ${{ env.LV_PYTHON_SCRIPTS_PATH }}\scripts\src\scripts\find_circular_paths.py --folder "${{ github.workspace }}\Source\ActualDependencies"

      - name: Commit dependency updates if needed
        shell: powershell
        run: |
          cd ${{ env.LV_PYTHON_SCRIPTS_PATH }}\scripts
          uv sync
          cd ${{ env.LV_PYTHON_SCRIPTS_PATH }}
          scripts\.venv\Scripts\activate
          uv run python -u ${{ env.LV_PYTHON_SCRIPTS_PATH }}\scripts\src\scripts\commit_adeps_changes.py --workspace "${{ github.workspace }}" --deps-file-path "Source\ActualDependencies\ActualDepsList.adeps" --branch "${{ github.event.pull_request.head.ref }}"