; PathConfigs.ini
; Configure which paths should be used for CI Checks..
; Paths are repository-relative (no drive / workspace prefix)
; Paths are given in key names of the sections.

; This section used to config LabVIEW version and bitness.
[LabVIEW]
Version = 2019
Bitness = 32

; This section lists the paths to be excluded for all the CI Checks.
[GlobalExcludePaths]
Docs = ""
Tests = ""
scripts = ""
Hawkeye = ""
.HawkeyeCache = ""

; This section lists the source folder paths to be included for all the CI Checks.
[SourceFolderPaths]
Source = ""

[BuildSpecsIncludePaths]
.HawkeyeCache = ""

; Only one path is supported currently in this section.
; Update the parameter values in the workflow YAML file if the ActualDepsIncludePaths paths are modified from the default configuration.
[ActualDepsIncludePaths]
Hawkeye\ActualDependencies = ""

[ChangedFilesLogs]
ChangedFilesListPath = ".HawkeyeCache\\Temp\\CheckModifiedLVFiles\\changed_files.txt"
ChangedLVFilesListPath = ".HawkeyeCache\\Temp\\CheckModifiedLVFiles\\changed_lvfiles.txt"
InScopeChangedLVFilesPath = ".HawkeyeCache\\Temp\\CheckModifiedLVFiles\\in_scope_changed_lvfiles.txt"
InScopeChangedLVLibsPath = ".HawkeyeCache\\Temp\\CheckModifiedLVFiles\\in_scope_changed_lvlibs.txt"
AllLibOrphanClassPath = ".HawkeyeCache\\Temp\\CheckModifiedLVFiles\\root_lvlib_lvclass.txt"

;Time in min to recreate cache files every CacheRecreateDuration exist.
[CacheConfig]
CacheRecreateDuration = 120