; PathConfigs.ini
; Configure which paths should be used for CI Checks..
; Paths are repository-relative (no drive / workspace prefix)
; Paths are given in key names of the sections.


; This section lists the paths to be excluded for all the CI Checks.
[GlobalExcludePaths]
Docs = ""
Tests = ""
scripts = ""

; This section lists the source folder paths to be included for all the CI Checks.
[SourceFolderPaths]
Source = ""


[BuildSpecsIncludePaths]
Source\BuildSpecs = ""

; Only one path is supported currently in this section.
[ActualDepsIncludePaths]
Source\ActualDependencies = ""

[ChangedFilesLogs]
ChangedFilesListPath = "CICD\\Temp\\CheckModifiedLVFiles\\changed_files.txt"
ChangedLVFilesListPath = "CICD\\Temp\\CheckModifiedLVFiles\\changed_lvfiles.txt"
InScopeChangedLVFilesPath = "CICD\\Temp\\CheckModifiedLVFiles\\in_scope_changed_lvfiles.txt"
InScopeChangedLVLibsPath = "CICD\\Temp\\CheckModifiedLVFiles\\in_scope_changed_lvlibs.txt"

############# Below Sections are not used currently ########

[CheckModifiedReportPaths]
UnExpectedDepsCheck = "CICD\\Reports\\CheckModifiedLVFiles\\UnexpectedDependenciesReport.txt"

[CheckAllReportPaths]
UnExpectedDepsCheck = "CICD\\Reports\\CheckAllLVFiles\\UnexpectedDependenciesReport.txt"

; This section lists the paths to be excluded specifically for certain CI Checks.
; NOTE: This is not used currently.
; Format: 
; Key name = <Check1>|<Path1>
; Key name = <Check1>|<Path2>
; Key name = <Check2>|<Path1>
; Key name = <Check2>|<Path2>
[ExcludePathsSpecificToChecks]
LibraryCheck|Prototypes = ""
LibraryCheck|Tests\UnitTests = ""

; This section is not used currently. This section is reserved for future use
; to implement additional paths for CI Checks excluding the Dependencies Check.
[GlobalIncludePaths]